### ISSUE TITLE
Base implementation.

### ISSUE THREAD

**Issue by thebearingedge** [thebearingedge/task#1]
# tasks
- [x] store fixtures of external service response bodies
- [x] test-drive gateways that can talk to each external service
  - [x] names
  - [x] jokes
- [x] compose gateways into an application
- [x] wrap in an HTTP server
- [x] dockerize
- [x] migrate from `just` to `make` for submission
- [x] add `TODO` comments
- [x] write readme
